package Vista;

import Controlador.GestionCarrera;
import Controlador.GestionCorredor;
import Informes.TestDataSource;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.File;
import java.io.IOException;
import java.io.Serializable;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.HashMap;
import java.util.Map;
import java.util.Timer;
import java.util.TimerTask;
import javax.help.HelpBroker;
import javax.help.HelpSet;
import javax.help.HelpSetException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRDataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import org.openide.util.Exceptions;

/**
 *
 * @author Jordy
 */
public class PantallaPrincipal extends javax.swing.JFrame implements Serializable {

    /**
     * Creates new form PantallaPrincipalOK
     */
    private GestionCorredor gCorredor = new GestionCorredor();
    private GestionCarrera gCarrera = new GestionCarrera();
    private transient Timer timer;
    private int tiempo = 0;
    private File fileCarreras = new File("datosCarrera.data");
    private File fileCorredores = new File("datosCorredores.data");
    private static final String RUTA_LOGO = "/imagenes/corredor1.jpg";

    public File getFile() {
        return fileCarreras;
    }

    public PantallaPrincipal() {
        initComponents();
        
        
        

        //Establecer el título de la aplicación
        setTitle("App Corredores");
        //que aparezca la ventana centrada
        this.setLocationRelativeTo(null);
        //Establecer el logo en el icono pequeño
        setIconImage(new ImageIcon(getClass().getResource(RUTA_LOGO)).getImage());
        guardadoAutomatico(5);
        ponerAyuda();
        if (fileCarreras.exists()) {
            try {
                gCarrera.leerEstado(fileCarreras.getAbsolutePath());
                gCorredor.leerEstado(fileCorredores.getAbsolutePath());
            } catch (IOException ex) {
                Exceptions.printStackTrace(ex);
            } catch (ClassNotFoundException ex) {
                Exceptions.printStackTrace(ex);
            }
        } else {
            try {
                gCorredor.guardarEstado(fileCorredores.getAbsolutePath());
                gCarrera.guardarEstado(fileCarreras.getAbsolutePath());
            } catch (IOException ex) {
                Exceptions.printStackTrace(ex);
            }
        }

        /**
         * Método que le pone un escuchador a la ventana principal y cuando se
         * cierra guarda el csv sin necesitad de darle al botón guardar
         * this.add... añade a ésta pantalla un listener de la ventana.
         * sobreescribir el método windowClosing y no confundir con windowClosed
         *
         */
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                try {
                    gCorredor.escribirCsvCorredores();
                    gCorredor.guardarEstado(fileCorredores.getAbsolutePath());
                    gCarrera.guardarEstado(fileCarreras.getAbsolutePath());
                } catch (IOException ex) {
                    Exceptions.printStackTrace(ex);
                }
            }
        });

    }

    private void ponerAyuda() {
        try {
            File ficheroAyuda = new File("help" + File.separator + "help_set.hs");
            URL hsURL = ficheroAyuda.toURI().toURL();

            //Crea el HelpSet y el HelpBroker
            HelpSet helpset = new HelpSet(getClass().getClassLoader(), hsURL);
            HelpBroker hb = helpset.createHelpBroker();

            hb.enableHelpOnButton(jButtonAyuda, "aplicacion", helpset);
            //Al pulsar F1 salta la ayuda
            hb.enableHelpKey(getRootPane(), "aplicacion", helpset);
            hb.enableHelpKey(jButtonCorredores, "ventanaCorredores", helpset);
            hb.enableHelpKey(jButtonCarreras, "ventanaCarreras", helpset);
            hb.enableHelpKey(jButtonGuardadoAuto, "aplicacion", helpset);
            hb.enableHelpKey(jButtonConfiguracion, "aplicacion", helpset);
        } catch (MalformedURLException ex) {
            Exceptions.printStackTrace(ex);
        } catch (HelpSetException ex) {
            Exceptions.printStackTrace(ex);
        }

    }

//    public void cambiarLookAndFeel() {
//        UIManager.setLookAndFeel(SeaGlassLookAndFeel.class.getCanonicalName());
//        SwingUtilities.updateComponentTreeUI(this);
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonCorredores = new javax.swing.JButton();
        jButtonCarreras = new javax.swing.JButton();
        jButtonConfiguracion = new javax.swing.JButton();
        jButtonGuardadoAuto = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonAyuda = new javax.swing.JButton();
        jLabelTitulo = new javax.swing.JLabel();
        jButtonInformes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonCorredores.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        jButtonCorredores.setText("CORREDORES");
        jButtonCorredores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCorredoresActionPerformed(evt);
            }
        });

        jButtonCarreras.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        jButtonCarreras.setText("CARRERAS");
        jButtonCarreras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCarrerasActionPerformed(evt);
            }
        });

        jButtonConfiguracion.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        jButtonConfiguracion.setText("Look And Feel");
        jButtonConfiguracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfiguracionActionPerformed(evt);
            }
        });

        jButtonGuardadoAuto.setFont(new java.awt.Font("Roboto Light", 0, 11)); // NOI18N
        jButtonGuardadoAuto.setText("Guardado automático");
        jButtonGuardadoAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardadoAutoActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/corredor1.jpg"))); // NOI18N

        jButtonAyuda.setFont(new java.awt.Font("Roboto Light", 0, 11)); // NOI18N
        jButtonAyuda.setText("AYUDA");
        jButtonAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAyudaActionPerformed(evt);
            }
        });

        jLabelTitulo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelTitulo.setText("APP CORREDORES");

        jButtonInformes.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jButtonInformes.setText("Informes");
        jButtonInformes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInformesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonCorredores)
                            .addComponent(jButtonGuardadoAuto))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(jButtonConfiguracion, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonCarreras, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 13, Short.MAX_VALUE))
                            .addComponent(jButtonInformes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelTitulo)
                        .addGap(85, 85, 85)
                        .addComponent(jButtonAyuda)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelTitulo)
                    .addComponent(jButtonAyuda))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonCorredores, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonCarreras, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGuardadoAuto)
                    .addComponent(jButtonConfiguracion)
                    .addComponent(jButtonInformes))
                .addGap(13, 13, 13))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCorredoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCorredoresActionPerformed
        ListadoCorredores listadoCorredores = new ListadoCorredores(this, true, gCorredor);
        listadoCorredores.setVisible(true);
    }//GEN-LAST:event_jButtonCorredoresActionPerformed

    private void jButtonCarrerasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCarrerasActionPerformed
        ListadoCarreras listadoCarreras = new ListadoCarreras(this, true, gCarrera, gCorredor);
        listadoCarreras.setVisible(true);

    }//GEN-LAST:event_jButtonCarrerasActionPerformed

    private void jButtonConfiguracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfiguracionActionPerformed
        ConfiguracionLookAndFeel configLA = new ConfiguracionLookAndFeel(this, true);
        configLA.setVisible(true);

    }//GEN-LAST:event_jButtonConfiguracionActionPerformed

    private void jButtonGuardadoAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardadoAutoActionPerformed
        String resultado = JOptionPane.showInputDialog("Introduce el tiempo de guardado automático en minutos.");
        tiempo = Integer.parseInt(resultado);
        guardadoAutomatico(tiempo);
    }//GEN-LAST:event_jButtonGuardadoAutoActionPerformed

    private void jButtonInformesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInformesActionPerformed
        PantallaInformes pantallaInformes = new PantallaInformes(this, true);
        pantallaInformes.setVisible(true);
    }//GEN-LAST:event_jButtonInformesActionPerformed

    private void jButtonAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAyudaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAyudaActionPerformed

    //si haces lista en vez de tabla
    /*public void rellenarListaCorredores() {

        DefaultListModel dlm = new DefaultListModel();
        for (Corredor listaCorredore : gc.getListaCorredores()) {
            dlm.addElement(listaCorredore);
        }
        jListCorredores.setModel(dlm);
    }*/
    public void guardadoAutomatico(int tiempoGuardado) {
        if (tiempoGuardado == 0) {
            tiempo = 5 * 60 * 1000;
        }
        tiempo = tiempoGuardado * 60 * 1000;
        if (timer == null) {
            timer = new Timer();
            timer.schedule(new TimerTask() {
                @Override
                public void run() {
                    try {
                        gCarrera.guardarEstado(fileCarreras.getAbsolutePath());
                        gCorredor.guardarEstado(fileCorredores.getAbsolutePath());
                    } catch (IOException ex) {
                        Exceptions.printStackTrace(ex);
                    }

                }
            }, tiempo);
        } else if (timer != null) {
            timer.cancel();
            timer = new Timer();
            timer.schedule(new TimerTask() {
                @Override
                public void run() {
                    try {
                        gCorredor.guardarEstado(fileCorredores.getAbsolutePath());
                        gCarrera.guardarEstado(fileCarreras.getAbsolutePath());
                    } catch (IOException ex) {
                        Exceptions.printStackTrace(ex);
                    }
                }
            }, tiempo);

        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAyuda;
    private javax.swing.JButton jButtonCarreras;
    private javax.swing.JButton jButtonConfiguracion;
    private javax.swing.JButton jButtonCorredores;
    private javax.swing.JButton jButtonGuardadoAuto;
    private javax.swing.JButton jButtonInformes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
