/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Informes.TestDataSource;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRDataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import org.openide.util.Exceptions;

/**
 *
 * @author Jordy
 */
public class PantallaInformes extends javax.swing.JDialog {

    /**
     * Creates new form PantallaInformes
     */
    public PantallaInformes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCarrerasSinFinalizar = new javax.swing.JLabel();
        jButtonCarrerasSinFinalizar = new javax.swing.JButton();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelCarrera = new javax.swing.JLabel();
        jButtonCarrera = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelCarrerasSinFinalizar.setText(org.openide.util.NbBundle.getMessage(PantallaInformes.class, "PantallaInformes.jLabelCarrerasSinFinalizar.text")); // NOI18N

        jButtonCarrerasSinFinalizar.setText(org.openide.util.NbBundle.getMessage(PantallaInformes.class, "PantallaInformes.jButtonCarrerasSinFinalizar.text")); // NOI18N
        jButtonCarrerasSinFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCarrerasSinFinalizarActionPerformed(evt);
            }
        });

        jLabelTitulo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelTitulo.setText(org.openide.util.NbBundle.getMessage(PantallaInformes.class, "PantallaInformes.jLabelTitulo.text")); // NOI18N

        jLabelCarrera.setText(org.openide.util.NbBundle.getMessage(PantallaInformes.class, "PantallaInformes.jLabelCarrera.text")); // NOI18N

        jButtonCarrera.setText(org.openide.util.NbBundle.getMessage(PantallaInformes.class, "PantallaInformes.jButtonCarrera.text")); // NOI18N
        jButtonCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCarreraActionPerformed(evt);
            }
        });

        jButton1.setText(org.openide.util.NbBundle.getMessage(PantallaInformes.class, "PantallaInformes.jButton1.text")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelCarrerasSinFinalizar)
                                    .addComponent(jLabelCarrera))
                                .addGap(194, 194, 194)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonCarrera)
                                    .addComponent(jButtonCarrerasSinFinalizar)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(263, 263, 263)
                        .addComponent(jLabelTitulo)))
                .addGap(118, 132, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitulo)
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCarrerasSinFinalizar)
                    .addComponent(jButtonCarrerasSinFinalizar))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCarrera)
                    .addComponent(jButtonCarrera))
                .addGap(63, 63, 63)
                .addComponent(jButton1)
                .addContainerGap(126, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCarrerasSinFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCarrerasSinFinalizarActionPerformed
        TestDataSource.listaCarreras();
        System.out.println(TestDataSource.listaCarreras().size());
        JRDataSource dataSource = new JRBeanCollectionDataSource(TestDataSource.listaCarreras());
        Map parametros = new HashMap();
        JasperPrint print;
        try {
            print = JasperFillManager.fillReport("informesPdf/reportPrueba.jasper", parametros, dataSource);
            JasperExportManager.exportReportToPdfFile(print, "informesPdf/InformeCarrerasPrueba.pdf");
        } catch (JRException ex) {
            Exceptions.printStackTrace(ex);
        }
        JOptionPane.showMessageDialog(this, "Informe creado en informesPdf");
    }//GEN-LAST:event_jButtonCarrerasSinFinalizarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCarreraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCarreraActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonCarrera;
    private javax.swing.JButton jButtonCarrerasSinFinalizar;
    private javax.swing.JLabel jLabelCarrera;
    private javax.swing.JLabel jLabelCarrerasSinFinalizar;
    private javax.swing.JLabel jLabelTitulo;
    // End of variables declaration//GEN-END:variables
}
