/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Logica.LogicaNegocio;
import de.javasoft.plaf.synthetica.SyntheticaOrangeMetallicLookAndFeel;

import java.util.List;
import java.util.Locale;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UIManager.LookAndFeelInfo;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;
import org.openide.util.Exceptions;

/**
 *
 * @author Jordy
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    private LogicaNegocio logicaNegocio = new LogicaNegocio();
    private static final String RUTA_LOGO = "/imgs/corredor1.jpg";

    public PantallaPrincipal() {
        initComponents();
        //que aparezca la ventana centrada
        this.setLocationRelativeTo(null);
        //Establecer una imagen en una label
        jLabelIcono.setIcon(new ImageIcon(getClass().getResource(RUTA_LOGO)));
        //Establecer el logo en el icono pequeño
        setIconImage(new ImageIcon(getClass().getResource(RUTA_LOGO)).getImage());
        //Establecer el título de la aplicación
        setTitle("App Corredores");

        //Instalación de Look And Feel de internet
        UIManager.installLookAndFeel(new UIManager.LookAndFeelInfo("Orange", SyntheticaOrangeMetallicLookAndFeel.class.getName()));

        /*HACER LA VENTANA DE UN TAMAÑO FIJO*/
        // this.setSize(600, 600);
        // this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jLabelIcono = new javax.swing.JLabel();
        jButonApariencia = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenuCorredores = new javax.swing.JMenu();
        jMenuItemDarAlta = new javax.swing.JMenuItem();
        jMenuItemMenu = new javax.swing.JMenuItem();
        jMenuCarreras = new javax.swing.JMenu();
        jMenuItemDarAltaCarrera = new javax.swing.JMenuItem();
        jMenuItemComenzarCarrera = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelTitulo.setText("App Corredores");

        jLabelIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/corredor1.jpg"))); // NOI18N

        jButonApariencia.setText("Look And Feel");
        jButonApariencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButonAparienciaActionPerformed(evt);
            }
        });

        jMenuCorredores.setText("Corredores");

        jMenuItemDarAlta.setText("Dar Alta Corredor");
        jMenuItemDarAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDarAltaActionPerformed(evt);
            }
        });
        jMenuCorredores.add(jMenuItemDarAlta);

        jMenuItemMenu.setText("Menu");
        jMenuItemMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMenuActionPerformed(evt);
            }
        });
        jMenuCorredores.add(jMenuItemMenu);

        jMenuBar2.add(jMenuCorredores);

        jMenuCarreras.setText("Carreras");
        jMenuCarreras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCarrerasActionPerformed(evt);
            }
        });

        jMenuItemDarAltaCarrera.setText("Dar alta carrera");
        jMenuItemDarAltaCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDarAltaCarreraActionPerformed(evt);
            }
        });
        jMenuCarreras.add(jMenuItemDarAltaCarrera);

        jMenuItemComenzarCarrera.setText("Comenzar carrera");
        jMenuItemComenzarCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemComenzarCarreraActionPerformed(evt);
            }
        });
        jMenuCarreras.add(jMenuItemComenzarCarrera);

        jMenuBar2.add(jMenuCarreras);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(jLabelTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButonApariencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelIcono, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(215, 215, 215))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jLabelTitulo)
                .addGap(29, 29, 29)
                .addComponent(jLabelIcono, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jButonApariencia)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemDarAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDarAltaActionPerformed
        DialogoAltaCorredor dialogoAlta = new DialogoAltaCorredor(this, true, logicaNegocio);
        dialogoAlta.setVisible(true);


    }//GEN-LAST:event_jMenuItemDarAltaActionPerformed

    private void jMenuCarrerasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCarrerasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuCarrerasActionPerformed

    private void jMenuItemMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMenuActionPerformed
        DialogoMenu dialogoMenu = new DialogoMenu(this, true, logicaNegocio);
        dialogoMenu.setVisible(true);
    }//GEN-LAST:event_jMenuItemMenuActionPerformed

    private void jButonAparienciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButonAparienciaActionPerformed
        LookAndFeel laf = new LookAndFeel(this, true);
        laf.setVisible(true);
    }//GEN-LAST:event_jButonAparienciaActionPerformed

    private void jMenuItemDarAltaCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDarAltaCarreraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemDarAltaCarreraActionPerformed

    private void jMenuItemComenzarCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemComenzarCarreraActionPerformed
        ComenzarCarrera comenzarCarrera = new ComenzarCarrera(this, true);
        comenzarCarrera.setVisible(true);
    }//GEN-LAST:event_jMenuItemComenzarCarreraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //Si la aplicación es en Español
                Locale.setDefault(new Locale("es", "ES"));
                new PantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButonApariencia;
    private javax.swing.JLabel jLabelIcono;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenu jMenuCarreras;
    private javax.swing.JMenu jMenuCorredores;
    private javax.swing.JMenuItem jMenuItemComenzarCarrera;
    private javax.swing.JMenuItem jMenuItemDarAlta;
    private javax.swing.JMenuItem jMenuItemDarAltaCarrera;
    private javax.swing.JMenuItem jMenuItemMenu;
    // End of variables declaration//GEN-END:variables
}
